name: CI - Run Cypress tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-server:
    name: Start Django server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        run: python manage.py migrate

      - name: Run Django server in background
        run: |
          nohup python manage.py runserver 0.0.0.0:8080 &
          sleep 10

  cypress-tests:
    name: Run Cypress Tests
    needs: start-server
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.1.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for Django server to be ready
        run: |
          apt-get update && apt-get install -y curl
          until curl --output /dev/null --silent --head --fail http://host.docker.internal:8080; do
            echo "Waiting for Django server..."
            sleep 2
          done

      - name: Run Cypress tests
        env:
          CYPRESS_baseUrl: http://host.docker.internal:8080
        run: npx cypress run
