name: Cypress Tests

on:
  push:
    branches:
      - main # seulement sur main (= default branch)
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    name: Run Cypress tests
    runs-on: ubuntu-latest

    container:
      image: cypress/included:13.1.0 # Image officielle de Cypress
      options: --user 1001 # pour éviter les problèmes de droits

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django server
        run: |
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8080 &
          sleep 10 # attend que le serveur démarre correctement

      - name: Run Cypress tests
        env:
          CYPRESS_baseUrl: http://localhost:8080
        run: |
          npx cypress run
