name: DAST
 
on:
  push:
    branches:
      - main
 
jobs:
  dast-scan:
    runs-on: ubuntu-latest
    continue-on-error: true
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Build and run the app
        run: |
          docker build -t my-app .
          docker run -d -p 8080:8080 --name my-app my-app
          sleep 15
 
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8080'
 
      - name: ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: report_json.json
 
      - name: Remove docker container
        if: always()
        run: |
          docker stop my-app || true
          docker rm my-app || true
 
 
