name: Build and Push Docker Image

on:
  push:
    branches: ["main", "develop", "feature/**"]

jobs:
  docker-build:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.meta.outputs.image_sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/isen-python:dev-${{ github.sha }}

      - name: Output image SHA
        id: meta
        run: echo "image_sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
