name: Static Application Security Testing (SAST)

on:
  push:
    branches: ["main", "develop", "feature/**"]
  pull_request:
    branches: ["main"]

jobs:
  bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -x unit_tests,integration_tests -lll
