name: Generate SBOM

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.15.10
        with:
          source: dir:.
          format: syft-json
          output-file: isen-python-generate-sbom.syft-json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-syft-json
          path: isen-python-generate-sbom.syft-json
