name: Generate SBOM

on:
  push:
    branches: ["main", "develop", "feature/**"]
  workflow_dispatch:

jobs:
  generate-sbom:
    name: Generate SBOM using Syft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate SBOM from source
        uses: anchore/sbom-action@v0.15.10
        with:
          path: .
          output-file: sbom.syft.json
          format: syft-json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.syft.json
